apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  MY_SECRET_ONE: VGhpcyBpcyBlbnZpcm9ubWVudCBvbmU # echo -n "This is environment one" | base64
  MY_SECRET_TWO: VGhpcyBpcyBlbnZpcm9ubWVudCB0d28= # echo -n "This is environment two" | base64
# stringData:
#   MY_SECRET_ONE: "This is environment one"
#   MY_SECRET_TWO: "This is environment two"

# kubectl apply -f secret.yaml

# kubectl create secret docker-registry my-registry-secret --docker-server="docker.io" \
# --docker-username="{ACRUsername}" \
# --docker-password="{ACRPassword}" \
# --docker-email="{DockerEmail}" \
# --namespace=development

# kubectl create secret tls tls-cert-secret \
# --namespace=development \
# --key=privkey.pem \
# --cert=cert.pem